import "./globals.css";
import {Poppins } from "next/font/google";

import type { Metadata } from "next";
const font = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Namaz Timer",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <head>
        <link rel="icons" href="/favicon.ico" className="bg-white"/>
        <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap" rel="stylesheet"></link>

      </head>
      <body className={font.className}>{children}</body>

    </html> 
    
   );
}
 
export default RootLayout;
